language: python

python:
  - "2.6"
  - "2.7"

addons:
  apt:
    packages:
      - bibutils

install:
  - pip install nose
  - pip install .

script:
  - export PATH=$PATH:$HOME/bin
  - python setup.py nosetests --verbosity=2

notifications:
  email: false
